services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real-estate
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - pnpm_store:/root/.pnpm-store
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://username:password@db:5432/realestate
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: realestate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5


  web:
    image: nginx:1.25.3-alpine
    container_name: real-estate-web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_healthy

volumes:
  postgres_data:
  pnpm_store: