version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real-estate
    ports:
      - "6000:6000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - pnpm_store:/root/.pnpm-store
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://jeremy:password@db:5432/realestate
    depends_on:
      - db
    command: sh -c "pnpm prisma migrate deploy && pnpm run start:dev"

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: jeremy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: realestate
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pnpm_store: